eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8081
spring:
  application:
    name: customer-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/CarWashCustomers

#swagger: '2.0'
#info:
#  version: 1.0.0
#  title: Based on "Basic Auth Example"
#  description: >
#    An example for how to use Auth with Swagger.
#
#host: localhost
#schemes:
#  - http
#  - https
#paths:
#  /:
#    get:
#      parameters:
#        -
#          name: authorization
#          in: header
#          type: string
#          required: true
#      responses:
#        '200':
#          description: 'Will send `Authenticated`'
#        '403':
#          description: 'You do not have necessary permissions for the resource'